apiVersion: v1
kind: ConfigMap
metadata:
  name: request-personal-information-configmap-production
  namespace: request-personal-information-production
data:
  RAILS_ENV: production
  SENTRY_CURRENT_ENV: production
  RAILS_SERVE_STATIC_FILES: enabled
  API_URL: "https://track-a-query.service.justice.gov.uk/api/rpi/"
  API_SCHEMA: "2"
  CLAMD_TCP_HOST: request-personal-information-clamav-service
  CLAMD_TCP_PORT: "3310"
