apiVersion: apps/v1
kind: Deployment
metadata:
  name: request-personal-information-production
  namespace: request-personal-information-production
spec:
  replicas: 3
  revisionHistoryLimit: 5
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxUnavailable: 0
      maxSurge: 100%
  selector:
    matchLabels:
      app: request-personal-information-web-production
  template:
    metadata:
      labels:
        app: request-personal-information-web-production
        tier: frontend
    spec:
      serviceAccountName: request-personal-information
      containers:
      - name: webapp
        image: 754256621582.dkr.ecr.eu-west-2.amazonaws.com/central-digital-product-team/request-personal-information-staging:production.latest
        imagePullPolicy: Always
        ports:
          - containerPort: 3000
        command: ["./config/docker/entrypoint-webapp.sh"]
        resources:
          requests:
            cpu: 125m
            memory: 500Mi
          limits:
            cpu: 250m
            memory: 1Gi
        readinessProbe:
          httpGet:
            path: /up
            port: 3000
            httpHeaders:
              - name: X-Forwarded-Proto
                value: https
              - name: X-Forwarded-Ssl
                value: "on"
          initialDelaySeconds: 15
          periodSeconds: 10
        livenessProbe:
          httpGet:
            path: /up
            port: 3000
            httpHeaders:
              - name: X-Forwarded-Proto
                value: https
              - name: X-Forwarded-Ssl
                value: "on"
          initialDelaySeconds: 30
          periodSeconds: 10
        envFrom:
          - configMapRef:
              name: request-personal-information-configmap-production
          - secretRef:
              name: app-secrets
        env:
          - name: DATABASE_URL
            valueFrom:
              secretKeyRef:
                name: rds-postgresql-instance-output
                key: url
          - name: S3_BUCKET
            valueFrom:
              secretKeyRef:
                name: s3-bucket-output
                key: bucket_name
      - name: jobs
        image: 754256621582.dkr.ecr.eu-west-2.amazonaws.com/central-digital-product-team/request-personal-information-staging:production.latest
        imagePullPolicy: Always
        ports:
          - containerPort: 3000
        command: ["./config/docker/entrypoint-jobs.sh"]
        envFrom:
          - configMapRef:
              name: request-personal-information-configmap-production
          - secretRef:
              name: app-secrets
        env:
          - name: DATABASE_URL
            valueFrom:
              secretKeyRef:
                name: rds-postgresql-instance-output
                key: url
          - name: S3_BUCKET
            valueFrom:
              secretKeyRef:
                name: s3-bucket-output
                key: bucket_name
      initContainers:
        - name: pending-migrations
          image: 754256621582.dkr.ecr.eu-west-2.amazonaws.com/central-digital-product-team/request-personal-information-staging:production.latest
          command:
            - /bin/sh
            - -c
            - 'bundle exec rake db:abort_if_pending_migrations'
          envFrom:
            - configMapRef:
                name: request-personal-information-configmap-production
            - secretRef:
                name: app-secrets
          env:
            - name: DATABASE_URL
              valueFrom:
                secretKeyRef:
                  name: rds-postgresql-instance-output
                  key: url
            - name: S3_BUCKET
              valueFrom:
                secretKeyRef:
                  name: s3-bucket-output
                  key: bucket_name
