test:
  service: DiskWithHost
  root: <%= Rails.root.join("tmp/storage") %>

local:
  service: DiskWithHost
  root: <%= Rails.root.join("storage") %>

amazon:
  service: S3
  bucket: <%= ENV["S3_BUCKET"] %>
