apiVersion: v1
kind: ConfigMap
metadata:
  name: request-personal-information-configmap-development
  namespace: request-personal-information-development
data:
  RAILS_ENV: development
  SENTRY_CURRENT_ENV: development
  RAILS_SERVE_STATIC_FILES: enabled
  API_URL: "https://qa.track-a-query.service.justice.gov.uk/api/rpi/v2"
